---
language: go
go:
  - "1.11"

python:
  - 2.7

services: docker

env:
  - distro: ubuntu1204
  - distro: ubuntu1210
  - distro: ubuntu1304
  - distro: ubuntu1310
  - distro: ubuntu1404
  - distro: ubuntu1410
  - distro: ubuntu1504
  - distro: ubuntu1510
  - distro: ubuntu1604
  - distro: ubuntu1610
  - distro: ubuntu1704
  - distro: ubuntu1710
  - distro: ubuntu1804
  - distro: ubuntu1810
  - distro: centos6
  - distro: centos7
  - distro: debian8
  - distro: debian9
  - distro: debian10
  - distro: fedora24
  - distro: fedora25
  - distro: fedora26
  - distro: fedora27
  - distro: fedora28

before_install:
  # Install dependencies:
  - sudo pip install --upgrade pip
  - sudo pip install ansible
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep && chmod +x $GOPATH/bin/dep 
  # ansible-role-tester consists of multiple Go packages, which refer to each other by
  # their absolute GitHub path, e.g. github.com/fubarhouse/ansible-role-tester/util.
  # This will break all travis tests in forks of this repo. We move the directory manually as a fix.
  - mkdir -p $TRAVIS_BUILD_DIR $GOPATH/src/github.com/fubarhouse
  - test ! -d $GOPATH/src/github.com/fubarhouse/ansible-role-tester && mv $TRAVIS_BUILD_DIR $GOPATH/src/github.com/fubarhouse/ansible-role-tester || true
  - export TRAVIS_BUILD_DIR=${TRAVIS_HOME}/gopath/src/github.com/fubarhouse/ansible-role-tester
  - cd ${TRAVIS_BUILD_DIR}
  # Install golang deps
  - dep ensure
  - go install ./...
  # Style checks
  - diff -u <(echo -n) <(gofmt -d $(find . -not -path "./vendor/*" -name "*.go"))
  - go vet $(go list ./... | grep -v /vendor/)
  # Download repos used in testing
  - git clone https://github.com/fubarhouse/ansible-role-curl.git ${TRAVIS_HOME}/my_role
  - git clone https://github.com/issmirnov/ansible-role-art-tester.git ${TRAVIS_HOME}/ansible-role-art-tester

script:
  # Test the role from inside the container using the segmented commands.
  - cd ${TRAVIS_HOME}/my_role
  - ansible-role-tester run --name travis_test --user fubarhouse --distribution ${distro}
  - ansible-role-tester install --name travis_test
  - ansible-role-tester test --name travis_test --playbook ./tests/test-package.yml
  - ansible-role-tester destroy --name travis_test
  - sleep 10
  # Change the test playbook to work with remote hosts (inventory)
  - sed -i -e 's/- hosts:\ localhost/- hosts:\ all/g' ${TRAVIS_HOME}/my_role/tests/test-package.yml
  # Change the test playbook to refer to the correct path for the role.
  - sed -i -e 's/role_under_test/\/home\/travis\/my_role\//g' ${TRAVIS_HOME}/my_role/tests/test-package.yml
  # Test the role from outside the container using the one standard pipeline command.
  - ansible-role-tester full --name travis_test --user fubarhouse --distribution ${distro} --playbook tests/test-package.yml --remote
  # Phase 2: test other flags
  - cd ${TRAVIS_HOME}/ansible-role-art-tester
  - ansible-role-tester full --playbook tests/playbook-library.yml --library "$(pwd)/tests/library"
  # Phase 3: run goconvey tests
  - cd ${TRAVIS_BUILD_DIR} && go test -short -v ./... 
