[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"
